name: Deploy to WordPress.org
on:
  push:
    branches:
      - main
      - master
    tags:
      - "*"
jobs:
  deploy:
    name: WordPress Plugin Deploy
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v2
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
